export enum GridId {
  journalsLedgersId = 1,
  trailBalanceId,
  accountId,
  accrualsId,
  logsId,
  filesId,
  tradeId,
  trailBalanceReportId,
  selectedAccrualsId,
  selectedTradeId,
  journalAllocationId,
  selectedJournalAllocationId,
  silverFilesId,
  gridLayoutsId,
  costBasisId,
  journalsId,
  fileExceptionId,
  closingTaxLotId,
  taxlotStatusId,
  taxlotId,
  fundTheoreticalId,
  dailyPnlId,
  taxRatesId,
  timeseriesId,
  marketPriceId,
  fxRateId,
  dayPnlReconcileId,
  bookMonReconcileId,
  taxlotsMaintenanceId,
  dividendsId,
  stockSplitsId,
  fundAdminReconcileId,
  allocationsId
}

export enum GridName {
  journalsLedgers = 'Journals Ledgers',
  trailBalance = 'Trail Balance',
  account = 'Account',
  accruals = 'Accruals',
  logs = 'Logs',
  files = 'Files',
  trade = 'Trade',
  trailBalanceReport = 'Trial Balance Report',
  selectedAccruals = 'Selected Accruals',
  SelectedTrades = 'Selected Trades',
  journalAllocation = 'Journal Allocation',
  selectedJournalAllocation = 'Selected Journal Allocation',
  silverFiles = 'Silver Files',
  gridLayouts = 'Grid Layouts',
  costBasis = 'Cost Basis',
  journals = 'Journals',
  fileException = 'File Exception',
  closingTaxLots = 'Closing TaxLots',
  taxlotStatus = 'Taxlot Status',
  taxlot = 'Taxlot',
  fundTheoretical = 'Fund Theoretical',
  dailyPnl = 'Daily PNL',
  taxRates = 'Tax Rates',
  timeseries = 'Cost Basis Time Series',
  marketPrice = 'Market Price',
  fxRate = 'Fx Rate',
  dayPnlReconcile = 'DayPnl Reconcile',
  bookmonReconcile = 'Bookmon Reconcile',
  taxlotsMaintenance = 'Tax Lots Maintenance',
  dividends = 'Dividends',
  stockSplits = 'Stock Splits',
  fundAdminReconcile = 'FundAdmin Reconcile',
  allocations = 'Allocations'
}
