CREATE TABLE [dbo].[security_details]
(
	[id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[security_id] INT NOT NULL,
	[symbol] VARCHAR(100) NOT NULL,
	[created_by] VARCHAR(100) NOT NULL, 
    [created_date] DATETIME NOT NULL, 
    [last_updated_by] VARCHAR(100) NULL, 
    [last_updated_date] DATETIME NULL, 
	[maturity_date] datetime NULL,
	[valuation_date] datetime NULL,
	[spread] numeric(22,8) NULL,
	[security_return_description] VARCHAR(MAX) NULL,
	[financing_leg] VARCHAR(MAX) NULL,
	[financing_end_date] datetime NULL,
	[financing_payment_date] datetime NULL,
	[financing_reset_date_type] VARCHAR(100) NULL,
	[financing_reset_date] VARCHAR(200) NULL,
	[next_financing_end_date_type] VARCHAR(100) NULL,
	[next_financing_end_date] VARCHAR(200) NULL,
	[fixed_rate] numeric(22,8) NULL,
	[dcc_fixed_rate] VARCHAR(100) NULL,
	[floating_rate] VARCHAR(100) NULL,
	[dcc_floating_rate] VARCHAR(100) NULL,
	[primary_market] VARCHAR(200) NULL,
	[reference_equity] numeric(22,8) NULL,
	[reference_obligation] numeric(22,8) NULL,
	[upfront] numeric(22,8) NULL,
	[premium_rate] numeric(22,8) NULL,
	[premium_frequency] numeric(22,8) NULL, 
    [active_flag] BIT NOT NULL DEFAULT 1
)
