CREATE TABLE [dbo].[unofficial_daily_pnl]
(
	[id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[created_by] NVARCHAR(100) NOT NULL,
	[created_date] datetime NOT NULL,
	[last_updated_by] NVARCHAR(100) NULL,
	[last_updated_date] datetime NULL,
	[business_date] datetime NOT NULL, 
    [portfolio] NVARCHAR(100) NULL, 
    [fund] NVARCHAR(100) NULL, 
    [trade_pnl] DECIMAL(18, 6) NOT NULL, 
    [day] DECIMAL(18, 6) NOT NULL, 
    [daily_percentage_return] DECIMAL(24, 16) NOT NULL, 
    [long_pnl] DECIMAL(18, 6) NOT NULL, 
    [long_percentage_change] DECIMAL(24, 16) NOT NULL, 
    [short_pnl] DECIMAL(18, 6) NOT NULL, 
    [short_percentage_change] DECIMAL(24, 16) NOT NULL, 
    [long_exposure] DECIMAL(18, 6) NOT NULL, 
    [short_exposure] DECIMAL(18, 6) NOT NULL, 
    [gross_exposure] DECIMAL(18, 6) NOT NULL, 
    [net_exposure] DECIMAL(18, 6) NOT NULL, 
    [six_md_beta_net_exposure] DECIMAL(18, 6) NOT NULL, 
    [two_yw_beta_net_exposure] DECIMAL(18, 6) NOT NULL, 
    [six_md_beta_short_exposure] DECIMAL(18, 6) NOT NULL, 
    [nav_market] DECIMAL(18, 6) NOT NULL, 
    [dividend_usd] DECIMAL(18, 6) NOT NULL, 
    [comm_usd] DECIMAL(18, 6) NOT NULL, 
    [fee_taxes_usd] DECIMAL(18, 6) NOT NULL, 
    [financing_usd] DECIMAL(18, 6) NOT NULL, 
    [other_usd] DECIMAL(18, 6) NOT NULL, 
    [pnl_percentage] DECIMAL(24, 16) NOT NULL, 
    [mtd_percentage_return] DECIMAL(24, 16) NOT NULL, 
    [qtd_percentage_return] DECIMAL(24, 16) NOT NULL, 
    [ytd_percentage_return] DECIMAL(24, 16) NOT NULL, 
    [itd_percentage_return] DECIMAL(24, 16) NOT NULL, 
    [mtd_pnl] DECIMAL(18, 6) NOT NULL, 
    [qtd_pnl] DECIMAL(18, 6) NOT NULL, 
    [ytd_pnl] DECIMAL(18, 6) NOT NULL, 
    [itd_pnl] DECIMAL(18, 6) NOT NULL 
)
