CREATE PROCEDURE [dbo].[SyncManualJournal]
	@journalId int
AS
	INSERT INTO [current_journal_full] ([when]
      ,[event]
      ,[credit]
      ,[debit]
      ,[symbol]
      ,[security_id]
      ,[quantity]
      ,[id]
      ,[account_id]
      ,[fx_currency]
      ,[fund]
      ,[AccountCategory]
      ,[AccountType]
      ,[accountName]
      ,[accountDescription]
      ,[value]
      ,[source]
      ,[start_price]
      ,[end_price]
      ,[fxrate]
      ,[is_account_to])
  SELECT [when]
      ,[event]
      ,[credit]
      ,[debit]
      ,[symbol]
      ,[security_id]
      ,[quantity]
      ,[id]
      ,[account_id]
      ,[fx_currency]
      ,[fund]
      ,[AccountCategory]
      ,[AccountType]
      ,[accountName]
      ,[accountDescription]
      ,[value]
      ,[source]
      ,[start_price]
      ,[end_price]
      ,[fxrate]
      ,[is_account_to]
	  FROM [vwJournal]
	  WHERE [vwJournal].[id] = @journalId;
RETURN 0